### ISSUE TITLE
Element IDs can (probably) be downsized from `u64` to `u32`

### ISSUE THREAD

**Issue by FreezyLemon** [rust-av/matroska#110]
Element IDs are variable-size integers. While EBML allows Element IDs that are larger than 4 octets, Matroska [restricts this](https://www.ietf.org/archive/id/draft-ietf-cellar-matroska-15.html#name-added-ebml-constraints):
> As an EBML Document Type, Matroska adds the following constraints to the EBML specification.
[...] * The EBMLMaxIDLength of the EBML Header MUST be 4.

This is true at least for elements [in the EBML Body](https://www.ietf.org/archive/id/draft-ietf-cellar-matroska-15.html#name-matroska-element-ids-regist):
> Element IDs are encoded using the VINT mechanism [...] and can be between one and five octets long. Five-octet-long Element IDs are possible only if declared in the EBML header.

I don't think that there are any EBML Header Elements that need more than 4 octets for the Element ID? I am not 100% sure, but at least for the entire EBML Body, `u32` can be used.

**Comment by Luni-4** [comment]
I agree with your observation, thanks for spotting that! Yep, we can change `u64` to `u32`

**Comment by FreezyLemon** [comment]
Depends on what you mean by "malformed input" exactly.

If we're just talking about the Element ID, the VINT format specifies its own length (very similar to UTF-8). So the size is "baked into" the actual integer itself. If the VINT size is wrong, too few or too many bytes would be consumed and just interpreted as an ID.

It is incredibly unlikely that a broken ID like this would match the ID we're looking for at that point. So that would result in a `nom::VerifyError` or whatever it's called, basically the `verify` combinator errors out because the function doesn't return `true`. In the case that it *does* match the ID, I'd assume that it would fail on the very next step, because it tries to parse the content of the Element and most likely fail on whatever the next Element ID is.

I should mention that I haven't actually tested this.

**Comment by Luni-4** [comment]
> Depends on what you mean by malformed input. It is relatively simple to add a check that `size <= 4` for Element IDs to have the parser just return something like `Ebml::ElementIDTooWide` or something similar.

I like this idea, we can implement that. 
 
> If you mean actual broken input: If the Element ID size is incorrect somehow, it is very unlikely to match the exact Element ID we have hardcoded into the parser. And if they don't match, the `verify` combinator will just error out.

Yeah, you're right, so let's add only the check above and then we can transform `u64` into `u32`
