### ISSUE TITLE
Support minOccurs = 1, maxOccurs = unbounded

### ISSUE THREAD

**Issue by FreezyLemon** [rust-av/matroska#129]
Parsing `Vec<T>` uses `nom::multi::many0`, so parsing will succeed even if there are zero elements.
There are some elements with minOccurs = 1, so to be compliant we'd need to fail parsing unless there is at least one element. `many1` would simply accomplish this, but it still needs to be implemented.

Maybe `Option<Vec<T>>` for 0..n elements, and `Vec<T>` for 1..n elements?
*Maybe* we can declare an `Option<Vec<T>>` in the macro and have it reduced to `Vec<T>` in the struct, while still using the correct parsing?

For example:
```rust
impl_ebml_master! {
    // Element ID 0x6D80
    #[derive(Debug, Clone, PartialEq, Eq)]
    struct ContentEncodings {
        [0x6240] content_encoding: (Option<Vec<ContentEncoding>>),
    }
}
```

but the struct will be

```rust
pub struct ContentEncodings {
  content_encoding: Vec<ContentEncoding>,
}

impl EbmlParsable for ContentEncodings {
  // simplified
  fn try_parse(data) -> Self {
    many0(inner_parser)(data)
  }
}
```

This would probably take some macro tinkering.

**Comment by Luni-4** [comment]
Instead of using `Option<Vec<T>` or `Vec<T>`, can't we define new types such as `ZeroToN<T>` and `OneToN<T>` and parse the right values accordingly?

**Comment by lu-zero** [comment]
[many_m_n](https://docs.rs/nom/7.1.3/nom/multi/fn.many_m_n.html) would be ideal and since it is a macro already you can just use a custom syntax 
``` rust
impl_ebml_master! {
    // Element ID 0x6D80
    #[derive(Debug, Clone, PartialEq, Eq)]
    struct ContentEncodings {
        [0x6240] content_encoding: (Vec<ContentEncoding> [M..N]),
    }
}
```
and map to the right many for [M..], [..N], or no range for many0.

**Comment by FreezyLemon** [comment]
I like both ideas.

`[M..N]` would be very flexible, but it might be "too much" for Matroska parsing. As of the latest draft, there's only one Element (SeekHead) that has a maxOccurs which is not `1` or `unbounded`. Realistically, we only need these following cases:
- [0..1] (-> `Option<T>`)
- 1 (-> `T`)
- [0..]
- [1..]

Newtypes like `OneToN` and `ZeroToN` would definitely work, and they would convey the behaviour to the API consumers which would be nice. One disadvantage would be that those types wouldn't be quite as ergonomic as a "standard" Vec without a lot of boilerplate.

How about this instead?

```rust
impl_ebml_master! {
    // Element ID 0x6D80
    #[derive(Debug, Clone, PartialEq, Eq)]
    struct ContentEncodings {
        [0x6240] content_encoding: (Vec<ContentEncoding> [1..]),
    }
}
```

If the `[1..]`/`[0..]` is missing, the `Vec<T>` doesn't get recognized as a vector of EBML elements, but just as some type which might implement `EbmlParsable` (like Vec<u8> for binary).

If the `[1..]`/`[0..]` is present, we do recognize it as a vector of EBML Elements and use `many1`/`many0`.

This way, we can handle `Vec<T>` for `T: !EbmlParsable` without edge case handling. For `T: EbmlParsable` we get `many0` or `many1` around the Element parser, and all while keeping `Vec<T>` as the output type. Plus it could be extended to handle `[M..N]` later, without API breakage.

**Comment by Luni-4** [comment]
I like this solution! I agree with your idea!
