### ISSUE TITLE
Convert matroska_info panic! to proper errors.

### ISSUE THREAD

**Issue by lu-zero** [rust-av/matroska#44]
- [ ] Create an `InfoError` that implements `std::error::Error` (using err-derive).
- [ ] Make the `fn main` signature return a result.
- [ ] Replace the panic!() with `?`

**Comment by Veykril** [comment]
I'd be interested in picking this one up.

**Comment by lu-zero** [comment]
Thank you for joining us :)

**Comment by Veykril** [comment]
Should this also get rid of `better_panic`?

**Comment by lu-zero** [comment]
it can stay in case something else breaks.
